### PR TITLE
I need vm_type.hpp to be shared

### PR DESCRIPTION
**Pull request by imkiva**

### CODE REVIEW

**Review by mikecovlee — CHANGES_REQUESTED** [review]
Can you rename the vm_types.hpp to comm_types.hpp?

**Comment by imkiva** [comment]
> Can you rename the vm_types.hpp to comm_types.hpp?

I think it would be better if we name it `shared_types.hpp`

**Comment by mikecovlee** [comment]
fine, do it and I will merge the pull request

**Comment by mikecovlee** [comment]
OK, I see it

**Pull request merged**
